spring.application.name=taskmanagerapi

spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_db
spring.datasource.username=iamavocadooo
spring.datasource.password=Yggdrasil

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

application.security.jwt.secret-key=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
application.security.jwt.expiration=86400000

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always